module.exports = {
  siteMetadata: {
    title: `Oak&Lotus Consulting`,
    description: `Wir rekrutieren Azubis, besetzen Ihre offenen Stellen und helfen bei der Intergration.`,
    url: `https://oalconsult.de`,
    author: `Oak&Lotus Consulting`,
    year: 2020,
    keywords: [
      "Fachkräfte",
      "Fachkraefte-Mangel-2020",
      "Demografischer-Wandel",
      "Kranken-Pflege",
      "Alten-Pflege",
      "Agentur-Fuer-Arbeit",
      "Personal-Vermittlung",
      "Pflege-Notstand",
      "Fachkräftemangel",
      "Fachkräftemangel 2020",
      "Demografischer Wandel Fachkräftemangel",
      "Fachkräftebedarf",
      "Mangel an Fachkräften",
      "Fachkräftemangel Krankenpflege",
      "Fachkräftemangel in der Altenpflege",
      "Altenpflege Fachkräftemangel",
      "Agentur für Arbeit Fachkräftemangel",
      "Fachkräftemangel Lösungsvorschläge",
      "Dehoga Fachkräftemangel",
      "Herausforderung Fachkräftemangel",
      "Employer Branding Fachkräftemangel",
      "Altenpflege",
      "Altenpflegehelfer",
      "Altenpflegehelferin",
      "Altenplegeausbildung",
      "Examinierte Altenpfleger",
      "Mobile Altenpflege",
      "Ambulante Altenpflege",
      "Vermittlung",
      "Anwerbung ausländische Fachkräfte",
      "Arbeitskräfte aus Vietnam",
      "Pflegefachkraft",
      "Vietnam",
      "Azubis Vietnam",
      "Azubis Vietnamesen",
      "Fachkraft Vietnamesen",
      "Fachkraft Vietnam",
      "Vietnamesen",
      "Hanoi",
      "Saigon",
      "Ho-Chi-Minh Stadt",
      "Dehoga",
      "Ausländerbehörde",
      "Fachpflegekraft",
      "Intensivpflege",
      "Altenheim",
      "Krankenhaus",
      "Klinik",
      "Klinikum",
    ],
  },
  plugins: [
    `gatsby-plugin-preact`,
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `index`,
        path: `${__dirname}/src/images`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `partner`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        icon: `src/images/favicon-32x32.png`,
      },
    },
    `gatsby-plugin-remove-serviceworker`,
  ],
}
